services:
  webdav-rd:
    image: ghcr.io/ebrainte/rd-dav-server:latest
    container_name: webdav-rd-client
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - RD_WEBDAV_URL=https://dav.real-debrid.com
      - RD_USERNAME=${RD_USERNAME}
      - RD_PASSWORD=${RD_PASSWORD}
      - OMDB_API_KEY=${OMDB_API_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - HOST=0.0.0.0
      - PORT=8080
      - CACHE_TTL=300
